In [1]:
# importing the libraries

import pandas as pd
import numpy as np

In [2]:
# reading the excel file
# by using concat reading the complete data that is present in ecxel file 
# reading the given data set in .xlsx file format

df=pd.concat(pd.read_excel("project1.xlsx",sheet_name=None),ignore_index=True)
df

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,NaN,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17
1,1539,MS-OPEN VALUE SUBSCRIPTION,059-07014,BA0025,NaN,"1YR WORD ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
2,1539,MS-OPEN VALUE SUBSCRIPTION,065-06444,BA0039,NaN,"1YR EXCEL ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
3,1539,MS-OPEN VALUE SUBSCRIPTION,076-04355,BA0067,NaN,"1YR PRJCT ALNG LICSAPK OLV D AP,",No Stock,0,217.60,2020-08-17
4,1582,MS-OPEN VALUE SUBSCRIPTION,077-05318,BA0080,NaN,"1YR ACCESS ALNG LICSAPK OLV D, AP",No Stock,0,56.09,2020-08-17
...,...,...,...,...,...,...,...,...,...,...
2627921,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627922,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627923,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627924,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627925,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28

In [3]:
# Getting complete information about data

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2627926 entries, 0 to 2627925
Data columns (total 10 columns):
 #   Column           Dtype
---  ------           -----
 0   category         int64
 1   manufacturer     object
 2   part_number      object
 3   sku              object
 4   alt_sku          object
 5   description      object
 6   status           object
 7   qty              int64
 8   price            float64
 9   sku_create_date  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 200.5+ MB

In [4]:
# getting starting 5 rows of data

df.head()

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,NaN,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17
1,1539,MS-OPEN VALUE SUBSCRIPTION,059-07014,BA0025,NaN,"1YR WORD ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
2,1539,MS-OPEN VALUE SUBSCRIPTION,065-06444,BA0039,NaN,"1YR EXCEL ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
3,1539,MS-OPEN VALUE SUBSCRIPTION,076-04355,BA0067,NaN,"1YR PRJCT ALNG LICSAPK OLV D AP,",No Stock,0,217.60,2020-08-17
4,1582,MS-OPEN VALUE SUBSCRIPTION,077-05318,BA0080,NaN,"1YR ACCESS ALNG LICSAPK OLV D, AP",No Stock,0,56.09,2020-08-17

In [5]:
# getting last 5 rows of data

df.tail()

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
2627921,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627922,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627923,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627924,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28
2627925,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28

In [6]:
# checking the null values that are present in the data

df.isnull()

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
0,False,False,False,False,True,False,False,False,False,False
1,False,False,False,False,True,False,False,False,False,False
2,False,False,False,False,True,False,False,False,False,False
3,False,False,False,False,True,False,False,False,False,False
4,False,False,False,False,True,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...,...
2627921,False,False,False,False,True,False,False,False,False,False
2627922,False,False,False,False,True,False,False,False,False,False
2627923,False,False,False,False,True,False,False,False,False,False
2627924,False,False,False,False,True,False,False,False,False,False
2627925,False,False,False,False,True,False,False,False,False,False

In [7]:
# checking the total null values count present in the data

df.isnull().sum()

category                 0
manufacturer             0
part_number              0
sku                      0
alt_sku            2613442
description              0
status                   0
qty                      0
price                    0
sku_create_date          0
dtype: int64

In [8]:
# The describe() method returns description of the data in the DataFrame

df.describe()

           category           qty         price
count  2.627926e+06  2.627926e+06  2.627926e+06
mean   2.379739e+03  4.138502e+01  1.882534e+03
std    2.776633e+03  5.802069e+02  8.202102e+04
min    1.000000e+00  0.000000e+00  0.000000e+00
25%    7.010000e+02  0.000000e+00  2.108000e+01
50%    1.535000e+03  0.000000e+00  9.531000e+01
75%    2.240000e+03  2.000000e+00  4.998400e+02
max    9.999000e+03  6.006300e+04  8.497453e+07

In [9]:
# getting rows and columns present in the data

df.shape

(2627926, 10)

In [10]:
# checking the size of the data

df.size

26279260

In [348]:
# droping duplicates from the data

df1 = df.drop_duplicates()
df1

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,NaN,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17
1,1539,MS-OPEN VALUE SUBSCRIPTION,059-07014,BA0025,NaN,"1YR WORD ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
2,1539,MS-OPEN VALUE SUBSCRIPTION,065-06444,BA0039,NaN,"1YR EXCEL ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
3,1539,MS-OPEN VALUE SUBSCRIPTION,076-04355,BA0067,NaN,"1YR PRJCT ALNG LICSAPK OLV D AP,",No Stock,0,217.60,2020-08-17
4,1582,MS-OPEN VALUE SUBSCRIPTION,077-05318,BA0080,NaN,"1YR ACCESS ALNG LICSAPK OLV D, AP",No Stock,0,56.09,2020-08-17
...,...,...,...,...,...,...,...,...,...,...
2627894,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.84,2020-08-28
2627895,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.77,2020-08-28
2627903,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.50,2020-08-28
2627912,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,51.88,2020-08-28
2627913,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28

In [349]:
# after droping the duplicates getting the data information

df1.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1105970 entries, 0 to 2627913
Data columns (total 10 columns):
 #   Column           Non-Null Count    Dtype
---  ------           --------------    -----
 0   category         1105970 non-null  int64
 1   manufacturer     1105970 non-null  object
 2   part_number      1105970 non-null  object
 3   sku              1105970 non-null  object
 4   alt_sku          6575 non-null     object
 5   description      1105970 non-null  object
 6   status           1105970 non-null  object
 7   qty              1105970 non-null  int64
 8   price            1105970 non-null  float64
 9   sku_create_date  1105970 non-null  datetime64[ns]
dtypes: datetime64[ns](1), float64(1), int64(2), object(6)
memory usage: 92.8+ MB

In [350]:
# by using groupby function selecting the column for seperation of data in thatcolumn

df1 = df1.groupby('status')

In [351]:
df1

# For data In Stock:

In [352]:
# by using get_group function to getting separation of 'In Stock' from 'status'

df2 = df1.get_group("In Stock")
df2

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
253,9920,CASE LOGIC-PERSONAL & PORTABLE,3200943,BA6371,NaN,"LAPTOP ROLLING CASE BLACK, SECURITY FRIENDLY 17IN",In Stock,7,99.00,2020-08-17
271,531,OMNITRON SYSTEMS,7206-0,BA6834,NaN,"1000BASE-SX SFP LC/MM/DF 850NM, 550M PLUGGABLE...",In Stock,2,59.09,2020-08-17
320,9070,ZEBRA ENTERPRISE MCD-A1,SAC5070-800CR,BC0227,NaN,"RS507 8SLOT BATTERY CHARGE KIT, EXT PWR SUPL/U...",In Stock,3,500.06,2020-08-17
324,9080,ZEBRA ENTERPRISE MCD-A1,KT-CLMPT-RS507-01R,BC0232,NaN,"RS507 TRIGGER SWIVEL DOES NOT, INCLUDE STRAP/B...",In Stock,115,86.34,2020-08-17
326,9080,ZEBRA ENTERPRISE MCD-A1,KT-PAD-RS507-10R,BC0234,NaN,"10 CT COMFORT PADS FOR RS507,",In Stock,42,51.80,2020-08-17
...,...,...,...,...,...,...,...,...,...,...
2627894,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.84,2020-08-28
2627895,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.77,2020-08-28
2627903,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.50,2020-08-28
2627912,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,51.88,2020-08-28
2627913,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28

## 1. Which are the top Manufacturers with price, quantity?

In [354]:
# finding the top manufacturers with price, quantity
# so, multiplying the quantity and price and creating a new column
# In my scenario top manufacturer will be desided based on the total price of manufacturer

df2["total_price"] = df2["qty"]*df["price"]
df2

C:\Users\SAIKIR~1\AppData\Local\Temp/ipykernel_25428/3100121902.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["total_price"] = df2["qty"]*df["price"]

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
253,9920,CASE LOGIC-PERSONAL & PORTABLE,3200943,BA6371,NaN,"LAPTOP ROLLING CASE BLACK, SECURITY FRIENDLY 17IN",In Stock,7,99.00,2020-08-17,693.00
271,531,OMNITRON SYSTEMS,7206-0,BA6834,NaN,"1000BASE-SX SFP LC/MM/DF 850NM, 550M PLUGGABLE...",In Stock,2,59.09,2020-08-17,118.18
320,9070,ZEBRA ENTERPRISE MCD-A1,SAC5070-800CR,BC0227,NaN,"RS507 8SLOT BATTERY CHARGE KIT, EXT PWR SUPL/U...",In Stock,3,500.06,2020-08-17,1500.18
324,9080,ZEBRA ENTERPRISE MCD-A1,KT-CLMPT-RS507-01R,BC0232,NaN,"RS507 TRIGGER SWIVEL DOES NOT, INCLUDE STRAP/B...",In Stock,115,86.34,2020-08-17,9929.10
326,9080,ZEBRA ENTERPRISE MCD-A1,KT-PAD-RS507-10R,BC0234,NaN,"10 CT COMFORT PADS FOR RS507,",In Stock,42,51.80,2020-08-17,2175.60
...,...,...,...,...,...,...,...,...,...,...,...
2627894,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.84,2020-08-28,7.68
2627895,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.77,2020-08-28,7.54
2627903,2240,BELKIN - CABLES,A3X126-10-RED,972494,NaN,"10FT CAT5E RED CROSSOVER CABLE, ROHS",In Stock,2,3.50,2020-08-28,7.00
2627912,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,51.88,2020-08-28,622.56
2627913,9945,VERBATIM CORPORATION,93975,986034,NaN,"CD & DVD TRIMPAK CASES 200PK, CLEAR FLEXIBLE P...",In Stock,12,50.53,2020-08-28,606.36

In [355]:
# arranging the total_price in high to low
# then using head() getting 1st 5 valuess from the obtained data

df2.sort_values("total_price", ascending=False).head()

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
2502762,1221,DELL ESG WARRANTIES,823-7912,7GZ792,NaN,"3YR NBD TO 5YR PROSPT 4H,",In Stock,9999,4236.30,2020-08-26,42358763.70
625985,1221,DELL CSG SERVICE WARRANTIES,818-6447,3DB700,NaN,"5YR PROSUPPORT PLUS,",In Stock,9999,3800.72,2020-08-17,38003399.28
1890636,1221,DELL CSG SERVICE WARRANTIES,818-6447,3DB700,NaN,"5YR PROSUPPORT PLUS,",In Stock,9999,3800.72,2020-08-24,38003399.28
2450786,1221,DELL CSG SERVICE WARRANTIES,818-6447,3DB700,NaN,"5YR PROSUPPORT PLUS,",In Stock,9999,3798.68,2020-08-26,37983001.32
2502761,1221,DELL ESG WARRANTIES,823-7911,7GZ791,NaN,"3YR NBD TO 5YR PROSPT 4H,",In Stock,9999,3111.01,2020-08-26,31106988.99

## 2. Which are the most profitable products?

In [262]:
# most profitable products will be the high qty with high price of the products 
# by using max() function getting the high total_price of the instock data

df2[df2.total_price==df2.total_price.max()]

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
2502762,1221,DELL ESG WARRANTIES,823-7912,7GZ792,NaN,"3YR NBD TO 5YR PROSPT 4H,",In Stock,9999,4236.3,2020-08-26,42358763.7

In [310]:
# total_price of the manufacturers are in high to low order wise below.
# from those products manufacturers are getting more money
# these are top 5 most profitable products

df2.sort_values("total_price", ascending=False).head()

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
2502762,1221,DELL ESG WARRANTIES,823-7912,7GZ792,NaN,"3YR NBD TO 5YR PROSPT 4H,",In Stock,9999,4236.30,2020-08-26,42358763.70
625985,1221,DELL CSG SERVICE WARRANTIES,818-6447,3DB700,NaN,"5YR PROSUPPORT PLUS,",In Stock,9999,3800.72,2020-08-17,38003399.28
1890636,1221,DELL CSG SERVICE WARRANTIES,818-6447,3DB700,NaN,"5YR PROSUPPORT PLUS,",In Stock,9999,3800.72,2020-08-24,38003399.28
2450786,1221,DELL CSG SERVICE WARRANTIES,818-6447,3DB700,NaN,"5YR PROSUPPORT PLUS,",In Stock,9999,3798.68,2020-08-26,37983001.32
2502761,1221,DELL ESG WARRANTIES,823-7911,7GZ791,NaN,"3YR NBD TO 5YR PROSPT 4H,",In Stock,9999,3111.01,2020-08-26,31106988.99

## 3. Which is the product where you have seen a decrease in the price?

In [274]:
# using sort_values to getting the decrease in the price of the products
# ascending = False is used to get the values in high to low

a = df2.sort_values("price", ascending = False)
a

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
1199874,521,HPE - SWITCHING,JL376A#B2B,6RN996,NaN,"ARUBA 8400 1 MM 3 PS 2 FM 32/8, BDL JMPCBL-NA/...",In Stock,3,69729.03,2020-08-20,209187.09
2620934,295,HPE - NIMBLE BTO,R3S72A,7JQ609,NaN,"HPE NS AF20 ALL FLASH 23TB BDL, 1 OR 3 YR SUPP...",In Stock,3,40893.99,2020-08-28,122681.97
2571702,295,HPE - NIMBLE BTO,R3S72A,7JQ609,NaN,"HPE NS AF20 ALL FLASH 23TB BDL, 1 OR 3 YR SUPP...",In Stock,2,40893.99,2020-08-27,81787.98
1203979,505,HPE - ARUBA INSTANT,JW830A,7U5737,NaN,"ARUBA 7240XM US FIPS/TAA, CONTROLLER PL=VL",In Stock,1,35554.13,2020-08-20,35554.13
1203946,505,HPE - ARUBA INSTANT,JW675A,7U4379,NaN,"7240XMDC CONTROLLER, PL=VL",In Stock,3,29385.55,2020-08-20,88156.65
...,...,...,...,...,...,...,...,...,...,...,...
258176,2201,C2G,01921,U40479,NaN,"RJ11 4X4 MOD PLUG FLAT STRND, CBL",In Stock,21,0.20,2020-08-17,4.20
1287203,1251,CONFIG 1,BTRY-MC55EAB00,CX4544,NaN,"MC55 STANDARD SPARE BATTERY, W/ LABEL SHEET ...",In Stock,71,0.00,2020-08-24,0.00
1287202,1251,CONFIG 1,SCX-5835FN - TAA,CX4513,NaN,"SCX-5835FN MONO LASER P/S/C/F,",In Stock,1,0.00,2020-08-24,0.00
21676,1251,CONFIG 1,SCX-5835FN - TAA,CX4513,NaN,"SCX-5835FN MONO LASER P/S/C/F,",In Stock,1,0.00,2020-08-17,0.00
21677,1251,CONFIG 1,BTRY-MC55EAB00,CX4544,NaN,"MC55 STANDARD SPARE BATTERY, W/ LABEL SHEET ...",In Stock,71,0.00,2020-08-17,0.00

In [361]:
# alternate method
# from this function also we can find that which product price is decreasing
# in this function I've used description in first, so we are getting the order of the products
# then after getting the order we can get by comparing the 10 days data with price to the products
# then we can sort that data and get the price decreasing product

df2.sort_values(by = ['description'], ascending = [False])

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
1669418,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,5,1156.32,2020-08-24,5781.60
404348,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,5,1156.32,2020-08-17,5781.60
2433897,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,3,1156.32,2020-08-26,3468.96
2350854,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,4,1156.32,2020-08-25,4625.28
1666825,32,SUPERMICRO - COMPONENTS,SSG-6038R-E1CR16L,ZN2792,NaN,"[NR]X10DRH-IT, CSE-836BTS-R920BP",In Stock,1,1927.91,2020-08-24,1927.91
...,...,...,...,...,...,...,...,...,...,...,...
1224096,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,21,23.93,2020-08-21,502.53
184623,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,23,23.93,2020-08-17,550.39
1224095,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,21,25.03,2020-08-21,525.63
2410442,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,20,25.03,2020-08-26,500.60
2410443,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,20,23.93,2020-08-26,478.60

## 4. Which is the product where you have seen an increase in the price?

In [304]:
# using sort_values to getting the decrease in the price of the products
# ascending = True is used to get the values in high to low

b = df2.sort_values("price", ascending = True)
b

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
1287203,1251,CONFIG 1,BTRY-MC55EAB00,CX4544,NaN,"MC55 STANDARD SPARE BATTERY, W/ LABEL SHEET ...",In Stock,71,0.00,2020-08-24,0.00
21676,1251,CONFIG 1,SCX-5835FN - TAA,CX4513,NaN,"SCX-5835FN MONO LASER P/S/C/F,",In Stock,1,0.00,2020-08-17,0.00
21677,1251,CONFIG 1,BTRY-MC55EAB00,CX4544,NaN,"MC55 STANDARD SPARE BATTERY, W/ LABEL SHEET ...",In Stock,71,0.00,2020-08-17,0.00
1287202,1251,CONFIG 1,SCX-5835FN - TAA,CX4513,NaN,"SCX-5835FN MONO LASER P/S/C/F,",In Stock,1,0.00,2020-08-24,0.00
258176,2201,C2G,01921,U40479,NaN,"RJ11 4X4 MOD PLUG FLAT STRND, CBL",In Stock,21,0.20,2020-08-17,4.20
...,...,...,...,...,...,...,...,...,...,...,...
1203946,505,HPE - ARUBA INSTANT,JW675A,7U4379,NaN,"7240XMDC CONTROLLER, PL=VL",In Stock,3,29385.55,2020-08-20,88156.65
1203979,505,HPE - ARUBA INSTANT,JW830A,7U5737,NaN,"ARUBA 7240XM US FIPS/TAA, CONTROLLER PL=VL",In Stock,1,35554.13,2020-08-20,35554.13
2571702,295,HPE - NIMBLE BTO,R3S72A,7JQ609,NaN,"HPE NS AF20 ALL FLASH 23TB BDL, 1 OR 3 YR SUPP...",In Stock,2,40893.99,2020-08-27,81787.98
2620934,295,HPE - NIMBLE BTO,R3S72A,7JQ609,NaN,"HPE NS AF20 ALL FLASH 23TB BDL, 1 OR 3 YR SUPP...",In Stock,3,40893.99,2020-08-28,122681.97
1199874,521,HPE - SWITCHING,JL376A#B2B,6RN996,NaN,"ARUBA 8400 1 MM 3 PS 2 FM 32/8, BDL JMPCBL-NA/...",In Stock,3,69729.03,2020-08-20,209187.09

In [358]:
# alternate method
# from this function also we can find that which product price is increasing
# in this function I've used description in first, so we are getting the order of the products
# then after getting the order we can get by comparing the 10 days data with price to the products

df2.sort_values(by = ['description'], ascending = [False])

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
1669418,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,5,1156.32,2020-08-24,5781.60
404348,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,5,1156.32,2020-08-17,5781.60
2433897,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,3,1156.32,2020-08-26,3468.96
2350854,32,SUPERMICRO - COMPONENTS,SYS-5018D-FN4T,ZQ8015,NaN,"[NR]XEON D X10SDV-TLN4F, 505-203B",In Stock,4,1156.32,2020-08-25,4625.28
1666825,32,SUPERMICRO - COMPONENTS,SSG-6038R-E1CR16L,ZN2792,NaN,"[NR]X10DRH-IT, CSE-836BTS-R920BP",In Stock,1,1927.91,2020-08-24,1927.91
...,...,...,...,...,...,...,...,...,...,...,...
1224096,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,21,23.93,2020-08-21,502.53
184623,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,23,23.93,2020-08-17,550.39
1224095,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,21,25.03,2020-08-21,525.63
2410442,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,20,25.03,2020-08-26,500.60
2410443,2240,TRIPP LITE CONNECTIVITY,N280-20N-BK,QZ7267,NaN,".5M PASSIVE TWINAX COPPER SFP+, CABLE 10GBASE-...",In Stock,20,23.93,2020-08-26,478.60

## 5. Which is the top category by price and quantity?

In [212]:
# here if we can get the max price value of product
# then that product category will be the top 
# so, here finding the max price value product
# '521' is the top category based on price

df2[df2.price==df2.price.max()]

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
1199874,521,HPE - SWITCHING,JL376A#B2B,6RN996,NaN,"ARUBA 8400 1 MM 3 PS 2 FM 32/8, BDL JMPCBL-NA/...",In Stock,3,69729.03,2020-08-20,209187.09

In [213]:
# here if we can get the max quantity of product
# then that product category will be the top 
# so, here finding the max quantity of product
# '1221' is the top category based on quantity

df2[df2.qty==df2.qty.max()]

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
2364017,1221,DELL CSG SERVICE WARRANTIES,808-3177,4A1885,NaN,"3YR NBD TO 3YR PROSUP NBD, OPTIPLEX",In Stock,60063,38.76,2020-08-25,2328041.88

## 6. Which products are aging?

In [254]:
# Taking the 1st day data
# arranginf quantity of products in high to low
# by using min( ) to day one detailes and sort_values to get quantity order in high to low 

df2_qty = df2[df2.sku_create_date==df2.sku_create_date.min()]
df2_qty.sort_values("qty", ascending=False).head(10)

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
680105,1221,DELL CSG SERVICE WARRANTIES,808-3177,4A1885,NaN,"3YR NBD TO 3YR PROSUP NBD, OPTIPLEX",In Stock,59995,38.76,2020-08-17,2325406.20
680090,1221,DELL CSG SERVICE WARRANTIES,808-3129,4A1842,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59995,267.10,2020-08-17,16024664.50
680080,1221,DELL CSG SERVICE WARRANTIES,808-3105,4A1818,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59994,84.24,2020-08-17,5053894.56
680086,1221,DELL CSG SERVICE WARRANTIES,808-3123,4A1836,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59994,129.96,2020-08-17,7796820.24
668949,9920,TMS,A4-DOCK-RELEASE,3V5945,NaN,"A4-DOCK-RELEASE,",In Stock,59994,85.00,2020-08-17,5099490.00
680084,1221,DELL CSG SERVICE WARRANTIES,808-3111,4A1824,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59994,201.79,2020-08-17,12106189.26
433175,1251,CONFIG 6,FEE SKU,1N4467,NaN,"INTEGRATION SVCS 175, $175",In Stock,59994,175.00,2020-08-17,10498950.00
680082,1221,DELL CSG SERVICE WARRANTIES,808-3108,4A1821,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59994,136.49,2020-08-17,8188581.06
680088,1221,DELL CSG SERVICE WARRANTIES,808-3126,4A1839,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59994,188.74,2020-08-17,11323267.56
852992,1241,TMS,A3 FREIGHT,6AA747,NaN,"A3 FREIGHT CHARGE,",In Stock,59994,125.00,2020-08-17,7499250.00

In [ ]:
# from below and above output
# now we can compare the the data present in both dates
# so, from the output if the quantity of the products not changes 
# then those products are aging
# from the output '1221' category of the products are still in stock. No sold much. So those are aging products

In [255]:
# Like above here Taking the last day data
# arranginf quantity of products in high to low
# by using max( ) to last day detailes and sort_values to get quantity order in high to low

df2_qty2 = df2[df2.sku_create_date==df2.sku_create_date.max()]
df2_qty2.sort_values("qty", ascending=False).head(10)

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date,total_price
2609950,1221,DELL CSG SERVICE WARRANTIES,808-3108,4A1821,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,60014,136.42,2020-08-28,8187109.88
2609948,1221,DELL CSG SERVICE WARRANTIES,803-5495,4A1807,NaN,"NOTEBOOK UPG TO 3YR ACCIDENTAL, DAMAGE",In Stock,59995,51.56,2020-08-28,3093342.20
2609949,1221,DELL CSG SERVICE WARRANTIES,808-3105,4A1818,NaN,"1YR HW SVC WITH IN-HOME/OS SVC, AFTER REM DIAG...",In Stock,59994,84.06,2020-08-28,5043095.64
2609952,1221,DELL CSG SERVICE WARRANTIES,808-3177,4A1885,NaN,"3YR NBD TO 3YR PROSUP NBD, OPTIPLEX",In Stock,59994,38.68,2020-08-28,2320567.92
2603984,303,HP INC. - SB DESKTOP DISPLAYS,1FH47A8#ABA,2CC558,NaN,"SMART BUY E243 ELITEDISPLAY, 23.8IN 1920X1080 ...",In Stock,31913,159.47,2020-08-28,5089166.11
2613028,1539,MICROSOFT- ESD,T5D-03190,5KU230,NaN,"OFFICE HOME AND BUSINESS 2019, ONLY DWNLD** NO...",In Stock,29998,216.94,2020-08-28,6507766.12
2609951,1221,DELL CSG SERVICE WARRANTIES,808-3174,4A1882,NaN,"3YR PROSUP NBD TO 3YR PROSUP, PLUS NBD LATITUDE",In Stock,29998,77.67,2020-08-28,2329944.66
2615307,1221,DELL ESG WARRANTIES,823-6205,6DB686,NaN,"1YR BASIC ONSITE TO 3YR PROSPT,",In Stock,29997,313.67,2020-08-28,9409158.99
2609953,1221,DELL CSG SERVICE WARRANTIES,808-3527,4A2082,NaN,"NOTEBOOK UPG TO 3YR KEEP YOUR, HARD DRIVE",In Stock,29997,14.21,2020-08-28,426257.37
2599136,1251,CONFIG 6,FEE SKU,YR8409,NaN,"INTEGRATION SVCS 1 3 4 LINE/LEV, 3",In Stock,26023,3.00,2020-08-28,78069.00

## 7. How to Decrease Product aging?

###### Tips to decrease Product aging :

* When product aging is noticed you have identified the aged stock from the aging inventory report and the age buckets of this stock, you will start marking down your products based on the age bucket they belong to.


* It is very important to apply the discount gradually and not just give a flat discount on everything, because when you give higher discount on more aged stocks you will make it more attractive to customer and this automatically ensures clearing those stocks faster than the newer ones.


* This gradual discount also ensures you are making the most money out of your stock, by not giving unnecessary discounts on stock that is not too old yet.


* Giving the offers like buy one and get one. Then aged products are going to decrease. And that offer will be more atrctive to customers. 'And picking the right price to the product is most importent'. Customer mindset is like that product is worth to the price or not. So in starting we can just expect normal profit on product, then we can gradually increase the price. It'll decrease product aging definitely. 


* social media utilization will be the great option to promote the product and decreasing of the product aging. Social media is a free space where we can connect with your customers daily. If your customer is using social media, you need to be using social media. This will keep you top of mind when they coonsider what they want or need to buy.

# For Data Not in Stock:

In [362]:
# by using get_group function to getting separation of 'No Stock' from 'status'

data = df1.get_group("No Stock")
data

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
0,1539,MS-OPEN VALUE SUBSCRIPTION,021-09108,BA0011,NaN,"1YR OFFICESTD ALNG LICSAPK OLV, D AP",No Stock,0,143.58,2020-08-17
1,1539,MS-OPEN VALUE SUBSCRIPTION,059-07014,BA0025,NaN,"1YR WORD ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
2,1539,MS-OPEN VALUE SUBSCRIPTION,065-06444,BA0039,NaN,"1YR EXCEL ALNG LICSAPK OLV D AP,",No Stock,0,56.09,2020-08-17
3,1539,MS-OPEN VALUE SUBSCRIPTION,076-04355,BA0067,NaN,"1YR PRJCT ALNG LICSAPK OLV D AP,",No Stock,0,217.60,2020-08-17
4,1582,MS-OPEN VALUE SUBSCRIPTION,077-05318,BA0080,NaN,"1YR ACCESS ALNG LICSAPK OLV D, AP",No Stock,0,56.09,2020-08-17
...,...,...,...,...,...,...,...,...,...,...
2627418,3360,TARGUS,AMB580TT,9X4546,NaN,"B580 BLUETOOTH MOUSE BLCK,",No Stock,0,19.53,2020-08-28
2627775,505,ENGENIUS,EAP1300,9Z0170,NaN,"11AC WAVE 2 INDOOR WRLS AP,",No Stock,0,85.24,2020-08-28
2627822,9910,KINGSTON,HX-MPFS-SM,9Z6619,NaN,"HYPERX FURY S PRO GAMING, MOUSE PAD SMALL",No Stock,0,13.75,2020-08-28
2627853,291,KINGSTON TECHNOLOGY FLASH,SD10VG2/16GBCP,9Z8507,NaN,"BULK 16GB SDHC CLASS 10 UHS-I, 45R MUST ORDER ...",No Stock,0,16.51,2020-08-28
2627857,291,KINGSTON,IKD300S/4GB,9103LA,NaN,"4GB D300S/D300SM AES 256 XTS, ENCRYPTED USB DRIVE",No Stock,0,52.83,2020-08-28

## 1. Which are the top Manufacturers with price, quantity?

In [188]:
# in this data, all products are out of stock 
# so, products are good value in market 
# here sorting the high price of products
# then top manufacturers will be the product which is having high price
# so, here top 5 manufacturers based on price and there is no quantity of the products

data.sort_values("price", ascending = False).head()

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
1046052,1231,ALTNET,ALT-TPM-240000000,6QN385,NaN,"ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...",No Stock,0,84974533.10,2020-08-17
2310142,1231,ALTNET,ALT-TPM-240000000,6QN385,NaN,"ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...",No Stock,0,84974533.10,2020-08-24
1046051,1231,ALTNET,ALT-TPM-80000000,6QN384,NaN,"ALTNET TPM UP TO 80000000 USD, LIST MNT UPTO 8...",No Stock,0,28324844.37,2020-08-17
2310141,1231,ALTNET,ALT-TPM-80000000,6QN384,NaN,"ALTNET TPM UP TO 80000000 USD, LIST MNT UPTO 8...",No Stock,0,28324844.37,2020-08-24
973610,1241,JUNIPER ROW SERVICES,SV5-SWA-JCE-1KGBPS,6JB451,NaN,"ROW 5YR SWA SUP FOR, JCE-1000GBPS",No Stock,0,10449000.00,2020-08-17

# 2. Which are the most profitable products?

In [372]:
# the most profitable product will be, the product which is having 0 quantity and high price
# so, here using max() function getting the product which is having high price 

data[data.price==data.price.max()]

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
1046052,1231,ALTNET,ALT-TPM-240000000,6QN385,NaN,"ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...",No Stock,0,84974533.1,2020-08-17
2310142,1231,ALTNET,ALT-TPM-240000000,6QN385,NaN,"ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...",No Stock,0,84974533.1,2020-08-24

# 3. Which is the product where you have seen a decrease in the price?

In [376]:
# so here using sort by function arranging dates and manufacturers in day wise
# by giving 'True' & ' False' getting prices in high to low
# from the output of the data we can see the decrease inthe price

data.sort_values(by = ['manufacturer', 'sku_create_date'], ascending = [False, True]).head(10)

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
213132,661,ZYXEL -LICENSING,ZYWALLVPN10,R35221,NaN,"ZYWALL IPSEC VPN CLIENT, 10 LICENSES VISTA SUP...",No Stock,0,330.65,2020-08-17
213133,661,ZYXEL -LICENSING,ZYWALLVPN10,R35221,NaN,"ZYWALL IPSEC VPN CLIENT, 10 LICENSES VISTA SUP...",No Stock,0,303.21,2020-08-17
213150,661,ZYXEL -LICENSING,ZYWALLVPN5,R35222,NaN,"ZYWALL IPSEC VPN CLIENT 5, LICENSE XP/VISTA SU...",No Stock,0,197.73,2020-08-17
213151,661,ZYXEL -LICENSING,ZYWALLVPN5,R35222,NaN,"ZYWALL IPSEC VPN CLIENT 5, LICENSE XP/VISTA SU...",No Stock,0,181.35,2020-08-17
213168,661,ZYXEL -LICENSING,ZYWALLVPN,R35223,NaN,"ZYWALL IPSEC VPN CLIENT 1, LICENSE XP/VISTA SU...",No Stock,0,50.11,2020-08-17
213169,661,ZYXEL -LICENSING,ZYWALLVPN,R35223,NaN,"ZYWALL IPSEC VPN CLIENT 1, LICENSE XP/VISTA SU...",No Stock,0,46.02,2020-08-17
238049,505,ZYXEL -LICENSING,ICAP8NXC2500,TX0040,NaN,"UPG NXC2500 8UG- NXC2500 ICARD, 8 AP LICS",No Stock,0,260.66,2020-08-17
238050,505,ZYXEL -LICENSING,ICAP8NXC2500,TX0040,NaN,"UPG NXC2500 8UG- NXC2500 ICARD, 8 AP LICS",No Stock,0,239.07,2020-08-17
271632,505,ZYXEL -LICENSING,ICAP8NXC5500,VR0064,NaN,"UPG NXC5500 8UG NXC5500, ICARD 8 AP LICS",No Stock,0,236.97,2020-08-17
271633,505,ZYXEL -LICENSING,ICAP8NXC5500,VR0064,NaN,"UPG NXC5500 8UG NXC5500, ICARD 8 AP LICS",No Stock,0,217.34,2020-08-17

# 4. Which is the product where you have seen an increase in the price?

In [369]:
# using sort by function getting order of all product in description
# and we can get the data in day wise
# as we see the output of data,if we compare product price in category '32' that is in 17 th date and 24th date
# product price is increasing

data.sort_values(by = ['description'], ascending = [False]).head(10)

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
425544,32,SUPERMICRO - COMPONENTS,SYS-6017R-WTRFTP+,1F4786,NaN,"[NR]X9DRW-ITPF + AND, CSE-819TQ-R700WB",No Stock,0,1221.72,2020-08-17
1690526,32,SUPERMICRO - COMPONENTS,SYS-6017R-WTRFTP+,1F4786,NaN,"[NR]X9DRW-ITPF + AND, CSE-819TQ-R700WB",No Stock,0,1221.72,2020-08-24
444510,5,SUPERMICRO - COMPONENTS,HNW0-15026364-HADP,1V3117,NaN,"[NR]X9DRW-IF CSE-815TQ-R500WB,",No Stock,0,4109.53,2020-08-17
1709345,5,SUPERMICRO - COMPONENTS,HNW0-15026364-HADP,1V3117,NaN,"[NR]X9DRW-IF CSE-815TQ-R500WB,",No Stock,0,4109.53,2020-08-24
1709346,32,SUPERMICRO - COMPONENTS,HNWX-19026364-HADP,1V3118,NaN,"[NR]X9DRW-7TPF 819TQ-R700WB,",No Stock,0,4094.95,2020-08-24
444511,32,SUPERMICRO - COMPONENTS,HNWX-19026364-HADP,1V3118,NaN,"[NR]X9DRW-7TPF 819TQ-R700WB,",No Stock,0,4094.95,2020-08-17
444480,32,SUPERMICRO - COMPONENTS,SYS-6027PR-DC0TR,1V3061,NaN,"[NR]X9DRT-PT, CSE-827HD+-R1K28BP",No Stock,0,2513.17,2020-08-17
1709313,32,SUPERMICRO - COMPONENTS,SYS-6027PR-DNCTR,1V3059,NaN,"[NR]X9DRT-PT, CSE-827HD+-R1K28BP",No Stock,0,2568.33,2020-08-24
1709315,32,SUPERMICRO - COMPONENTS,SYS-6027PR-DC0TR,1V3061,NaN,"[NR]X9DRT-PT, CSE-827HD+-R1K28BP",No Stock,0,2513.17,2020-08-24
444478,32,SUPERMICRO - COMPONENTS,SYS-6027PR-DNCTR,1V3059,NaN,"[NR]X9DRT-PT, CSE-827HD+-R1K28BP",No Stock,0,2568.33,2020-08-17

# 5. Which is the top category by price and quantity?

In [375]:
# in this no stock data, products are not in stock. So there is no quantity
# by using max() function getting the high price that which product is having
# so here the product price of category '1231' is high. so '1231' is top category

data[data.price==data.price.max()]

,category,manufacturer,part_number,sku,alt_sku,description,status,qty,price,sku_create_date
1046052,1231,ALTNET,ALT-TPM-240000000,6QN385,NaN,"ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...",No Stock,0,84974533.1,2020-08-17
2310142,1231,ALTNET,ALT-TPM-240000000,6QN385,NaN,"ALTNET TPM UP TO 240000000 USD, LIST MNT UPTO ...",No Stock,0,84974533.1,2020-08-24